version: '3.7'

services:
  filebeat:
    build: .
    env_file: 
      - ../common/common.env
    volumes:
      - ../logs/nginx:/var/log/nginx
    networks:
      - elk-nw

  nginx:
    image: nginx
    env_file: 
      - ../common/common.env
    ports:
      - "81:80"
    volumes:
      - ../logs/nginx:/var/log/nginx
    depends_on:
      - filebeat
    networks:
      - elk-nw

networks:
  elk-nw:
    external:
      name: kibana_elk-nw