version: '3.7'

services:
  elasticsearch:
    build: ./elasticsearch
    env_file: 
      - ./common/common.env
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-nw

  kibana:
    image: kibana:7.1.1
    env_file: 
      - ./common/common.env
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk-nw

networks:
  elk-nw:
