version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    env_file: 
      - ./common/common.env
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    links:
      - elasticsearch
    networks:
      - elk-nw

  elasticsearch:
    build: ./elasticsearch
    env_file: 
      - ./common/common.env
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    # volumes:
    #   - ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    #   - es-data:/usr/share/elasticsearch/data/
    links:
      - filebeat
    networks:
      - elk-nw

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:6.7.0
  #   volumes:
  #     - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro
  #   links:
  #     - filebeat
  #   networks:
  #     - elk-nw

  filebeat:
    build: ./filebeat
    env_file: 
      - ./common/common.env
    volumes:
      - ./logs/nginx:/var/log/nginx
    links:
      - nginx
    networks:
      - elk-nw

  nginx:
    image: nginx
    env_file: 
      - ./common/common.env
    ports:
      - "81:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - elk-nw

networks:
  elk-nw:
