version: '3.7'

services:
  elasticsearch:
    build: .
    env_file: 
      - ../common/common.env
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    # volumes:
    #   - ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    #   - es-data:/usr/share/elasticsearch/data/
    # command: 'sleep 10s'
    networks:
      - elk-nw

networks:
  elk-nw:
    external:
      name: kibana_elk-nw